### ISSUE TITLE
Trial -- not really an issue!  

### ISSUE THREAD

**Issue by Walker2310** [zross/hei_globalBurden#13]
This is easy.

**Comment by zross** [comment]
@Walker2310 I got this, see that if you use a "#" it references an issue. Like this #12 . Also note that I'm alerting you directly with "@Walker2310" but you don't need to do this for me since I'm "watching" this repository and get all messages automatically. Hollie will also see them automatically.

**Comment by mbrauerbc** [comment]
Just adding that I am on as well....

**Comment by zross** [comment]
Great!
